# Generated by Django 3.2.2 on 2021-08-04 19:22

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='SitAPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('price', models.FloatField()),
                ('sexe', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=250)),
                ('pets', models.BooleanField(blank=True, max_length=250, null=True)),
                ('garden', models.BooleanField(blank=True, max_length=250, null=True)),
                ('house', models.BooleanField(blank=True, max_length=250, null=True)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.race')),
                ('user', models.ForeignKey(default=accounts.models.Account, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('user', models.ForeignKey(default=accounts.models.Account, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellAPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sexe', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=250)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.race')),
                ('user', models.ForeignKey(default=accounts.models.Account, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonateAPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('quantity', models.IntegerField()),
                ('sexe', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=250)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='seting_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.race')),
                ('user', models.ForeignKey(default=accounts.models.Account, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
