# Generated by Django 3.2.2 on 2021-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211006_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_cover_img', models.ImageField(upload_to='seting_image/')),
                ('small_cover_img', models.ImageField(upload_to='seting_image/')),
                ('section1_title', models.CharField(max_length=30)),
                ('section1_img1', models.ImageField(upload_to='seting_image/')),
                ('section1_desc1', models.CharField(max_length=50)),
                ('section1_img2', models.ImageField(upload_to='seting_image/')),
                ('section1_desc2', models.CharField(max_length=50)),
                ('section1_img3', models.ImageField(upload_to='seting_image/')),
                ('section1_desc3', models.CharField(max_length=50)),
                ('news', models.CharField(max_length=30)),
                ('section2_title1', models.CharField(max_length=30)),
                ('section2_desc1', models.CharField(max_length=30)),
                ('section2_title2', models.CharField(max_length=30)),
                ('section2_desc2', models.CharField(max_length=30)),
                ('section2_title3', models.CharField(max_length=30)),
                ('section2_desc3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('named', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
