# Generated by Django 3.2.2 on 2021-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_home_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cover_title',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
