# Generated by Django 3.2.2 on 2021-10-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_home_cover_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Homes',
        ),
    ]
