# Generated by Django 3.2.2 on 2021-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211006_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2',
            name='section2_desc',
        ),
        migrations.AddField(
            model_name='section2',
            name='section2_desc1',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='section2',
            name='section2_desc2',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='section2',
            name='section2_title',
            field=models.CharField(max_length=20),
        ),
    ]
