# Generated by Django 3.2.2 on 2021-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211007_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='section2',
            name='section2_img',
            field=models.ImageField(null=True, upload_to='seting_image/'),
        ),
    ]
