# Generated by Django 3.2.2 on 2021-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_section2_section2_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(null=True, upload_to='seting_image/'),
        ),
    ]
