# Generated by Django 3.2.2 on 2021-10-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_testimonial_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='named',
            new_name='name',
        ),
    ]
